# Config version
version: 0.3.5

# HTML Head settings
html:
  title: "La Crypta | Links"
  google_analytics: "GTM-WZGV6DS"

# Theme settings
theme:
  # background_color: "white"
  cover_color: "#ff7070"

# Main container settings
main:
  title: "LA CRYPTA"
  # just replace your local file /public/images/profile.png

# Blocks list
blocks:
  - title: "Telegram"
    icon: "telegram"
    url: "https://t.me/lacryptaok"

  - title: "Twitter"
    icon: "twitter"
    url: "https://twitter.lacrypta.com.ar"

  - title: "Instagram"
    icon: "instagram"
    url: "https://instagram.lacrypta.com.ar"

  - title: "Discord"
    icon: "discord"
    url: "https://discord.lacrypta.com.ar"

  - title: "Nostr"
    icon: "nostr"
    url: "https://iris.to/lacrypta@hodl.ar"

  - title: "Github"
    icon: "github"
    url: "https://github.lacrypta.com.ar"

  - title: "Sitio Web"
    icon: "url"
    url: "https://www.lacrypta.com.ar/"

  - title: "Donaciones"
    icon: "lightning"
    url: "https://39ad255340.d.voltageapp.io/lnurlp/link/JJ9Sn5"
